import type { SchemaResponse, DatabaseProvider } from "./types";

// Active provider for the mock session
export const MOCK_PROVIDER: DatabaseProvider = "postgres";

// Representative schema covering all major relation patterns:
// one-to-many, many-to-many, and self-referential
export const MOCK_SCHEMA: SchemaResponse = {
  tables: [
    {
      name: "users",
      schema: "public",
      fields: [
        {
          name: "id",
          type: "serial",
          nullable: false,
          isPrimaryKey: true,
          isForeignKey: false,
          defaultValue: null,
        },
        {
          name: "email",
          type: "varchar",
          nullable: false,
          isPrimaryKey: false,
          isForeignKey: false,
          defaultValue: null,
        },
        {
          name: "username",
          type: "varchar",
          nullable: false,
          isPrimaryKey: false,
          isForeignKey: false,
          defaultValue: null,
        },
        {
          name: "created_at",
          type: "timestamptz",
          nullable: false,
          isPrimaryKey: false,
          isForeignKey: false,
          defaultValue: "now()",
        },
      ],
    },
    {
      name: "posts",
      schema: "public",
      fields: [
        {
          name: "id",
          type: "serial",
          nullable: false,
          isPrimaryKey: true,
          isForeignKey: false,
          defaultValue: null,
        },
        {
          name: "user_id",
          type: "integer",
          nullable: false,
          isPrimaryKey: false,
          isForeignKey: true,
          defaultValue: null,
        },
        {
          name: "title",
          type: "varchar",
          nullable: false,
          isPrimaryKey: false,
          isForeignKey: false,
          defaultValue: null,
        },
        {
          name: "body",
          type: "text",
          nullable: true,
          isPrimaryKey: false,
          isForeignKey: false,
          defaultValue: null,
        },
        {
          name: "created_at",
          type: "timestamptz",
          nullable: false,
          isPrimaryKey: false,
          isForeignKey: false,
          defaultValue: "now()",
        },
      ],
    },
    {
      name: "comments",
      schema: "public",
      fields: [
        {
          name: "id",
          type: "serial",
          nullable: false,
          isPrimaryKey: true,
          isForeignKey: false,
          defaultValue: null,
        },
        {
          name: "post_id",
          type: "integer",
          nullable: false,
          isPrimaryKey: false,
          isForeignKey: true,
          defaultValue: null,
        },
        {
          name: "user_id",
          type: "integer",
          nullable: false,
          isPrimaryKey: false,
          isForeignKey: true,
          defaultValue: null,
        },
        {
          name: "body",
          type: "text",
          nullable: false,
          isPrimaryKey: false,
          isForeignKey: false,
          defaultValue: null,
        },
        {
          name: "parent_id",
          type: "integer",
          nullable: true,
          isPrimaryKey: false,
          isForeignKey: true,
          defaultValue: null,
        },
      ],
    },
    {
      name: "tags",
      schema: "public",
      fields: [
        {
          name: "id",
          type: "serial",
          nullable: false,
          isPrimaryKey: true,
          isForeignKey: false,
          defaultValue: null,
        },
        {
          name: "name",
          type: "varchar",
          nullable: false,
          isPrimaryKey: false,
          isForeignKey: false,
          defaultValue: null,
        },
        {
          name: "slug",
          type: "varchar",
          nullable: false,
          isPrimaryKey: false,
          isForeignKey: false,
          defaultValue: null,
        },
      ],
    },
    {
      name: "post_tags",
      schema: "public",
      fields: [
        {
          name: "post_id",
          type: "integer",
          nullable: false,
          isPrimaryKey: true,
          isForeignKey: true,
          defaultValue: null,
        },
        {
          name: "tag_id",
          type: "integer",
          nullable: false,
          isPrimaryKey: true,
          isForeignKey: true,
          defaultValue: null,
        },
      ],
    },
    {
      name: "sessions",
      schema: "public",
      fields: [
        {
          name: "id",
          type: "uuid",
          nullable: false,
          isPrimaryKey: true,
          isForeignKey: false,
          defaultValue: "gen_random_uuid()",
        },
        {
          name: "user_id",
          type: "integer",
          nullable: false,
          isPrimaryKey: false,
          isForeignKey: true,
          defaultValue: null,
        },
        {
          name: "expires_at",
          type: "timestamptz",
          nullable: false,
          isPrimaryKey: false,
          isForeignKey: false,
          defaultValue: null,
        },
      ],
    },
  ],
  relations: [
    {
      constraintName: "posts_user_id_fkey",
      sourceTable: "posts",
      sourceField: "user_id",
      targetTable: "users",
      targetField: "id",
    },
    {
      constraintName: "comments_post_id_fkey",
      sourceTable: "comments",
      sourceField: "post_id",
      targetTable: "posts",
      targetField: "id",
    },
    {
      constraintName: "comments_user_id_fkey",
      sourceTable: "comments",
      sourceField: "user_id",
      targetTable: "users",
      targetField: "id",
    },
    {
      constraintName: "comments_parent_id_fkey",
      sourceTable: "comments",
      sourceField: "parent_id",
      targetTable: "comments",
      targetField: "id",
    },
    {
      constraintName: "post_tags_post_id_fkey",
      sourceTable: "post_tags",
      sourceField: "post_id",
      targetTable: "posts",
      targetField: "id",
    },
    {
      constraintName: "post_tags_tag_id_fkey",
      sourceTable: "post_tags",
      sourceField: "tag_id",
      targetTable: "tags",
      targetField: "id",
    },
    {
      constraintName: "sessions_user_id_fkey",
      sourceTable: "sessions",
      sourceField: "user_id",
      targetTable: "users",
      targetField: "id",
    },
  ],
};
